# Generated by Django 3.1.2 on 2020-10-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllStatesDaily',
            fields=[
                ('date', models.DateTimeField()),
                ('state', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('fips', models.IntegerField()),
                ('cases', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('updated', models.BigIntegerField()),
            ],
            options={
                'db_table': 'all_states_daily',
                'managed': True,
                'unique_together': {('state', 'date')},
            },
        ),
    ]
