# Generated by Django 3.1.2 on 2020-10-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allstatesdaily',
            name='cases',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='allstatesdaily',
            name='deaths',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='allstatesdaily',
            name='fips',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='allstatesdaily',
            name='updated',
            field=models.BigIntegerField(null=True),
        ),
    ]
