# Generated by Django 3.1.2 on 2020-10-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rad', '0002_auto_20201029_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsaDaily',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
                ('cases', models.IntegerField(blank=True, null=True)),
                ('deaths', models.IntegerField(blank=True, null=True)),
                ('updated', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usa_daily',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='allstatesdaily',
            options={'managed': False},
        ),
    ]
